gnosischain/documentation

- src/css/custom.css
- In light theme, the links are not easily recognizable. Adding bold and making the color palette easier to identify.
- Issue #29
> Closes #29

- CONTRIBUTING.md
- docusaurus.config.js
- repo name was changed to `documentation`
> repo name change

- docs/developers/verify/truffle.md
- Truffle Verify now supports gnosisscan and Gnosis.
- #93 
- [PR](https://github.com/rkalis/truffle-plugin-verify/pull/175)
> Truffle Verify native support

- docs/developers/building/first-contract.md
- docs/tools/faucets/README.md
- Fix minor typo
- Replace "Gnosis" with "xDai" as being required for contract deployment.
> Fix minor typos

- .github/ISSUE_TEMPLATE/suggest_dapp.yaml
- adding suggest dapp issue template
- #123 
- using Ethereum site as a base for this template: https://github.com/ethereum/ethereum-org-website/blob/dev/.github/ISSUE_TEMPLATE/suggest_dapp.yaml
> Suggest dapp issue template

- docs/node/guide/validator/_partials/clients/_install_validator_lighthouse.md
Add `\` line breaks to the Lighthouse VC docs. Presently, if a user copy-pastes this command it won't work. Additionally, other commands have line breaks so this makes things more consistent.
- Raised as an issue by another user in the Lighthouse Discord channel: https://discord.com/channels/605577013327167508/746918775919738893/1047334188157775925
> Add line breaks to Lighthouse VC docs

- docs/ecosystems/infrastructure.md
Adding Etherspot SDK to ecosystem page. Etherspot supportsGnosis/xDai chain from a while ago. 
Web: https://etherspot.io/  
Docs: https://docs.etherspot.dev/  
Email: [marketing@etherspot.io](mailto:marketing@etherspot.io)
> Add Etherspot SDK

- docs/node/guide/execution/erigon.md
this page mentions Nethermind twice in the instructions for Erigon where it was clearly a typo/copy-paste issue.  Kept note about Erigon not being production ready and that Nethermind is the preferred EL client, just fixed 2 typos
> replace nethermind in erigon instructions

- docs/node/tools/sedge.md
chiado docs link no longer resolves, I replaced the link with the current working URL https://docs.sedge.nethermind.io/docs/networks/chiado
chiado docs link https://docs.sedge.nethermind.io/docs/quickstart/chiado no longer resolves 
Replaced broken link for the nethermind sedge chiado instructions to a link that does resolve  https://docs.sedge.nethermind.io/docs/networks/chiado
> Update broken link for Chiado

- docs/ecosystems/nfts.md
- Add Hologram Project to NFT List
- Hologram is a platform that uses AI to generate art and turn it into NFT
- We had our Twitter Space with Gnosis Builders https://twitter.com/gnosisbuilders/status/1668647423064051712?s=20
> Add Hologram to NFT Project

- docs/developers/README.md
- docs/developers/building/full-stack-dapp.md
- docs/developers/smart-contracts/foundry.md
- docs/developers/smart-contracts/hardhat.md
- docs/developers/smart-contracts/truffle.mdx
- docs/node/guide/validator/_partials/_generate_validator_keys_cli.md
- docs/tools/README.md
- docs/tools/beacon-chain/liquid-staking.md
Hey :wave:,
This PR will fix :
1 typo in `docs/developers/README.md`
4 typos in `docs/developers/building/full-stack-dapp.md`
1 typo in `docs/developers/smart-contracts/foundry.md`
1 typo in `docs/developers/smart-contracts/hardhat.md`
2 typos in `docs/developers/smart-contracts/truffle.mdx`
1 typo in `docs/node/guide/validator/_partials/_generate_validator_keys_cli.md`
1 typo in `docs/tools/README.md`
1 typo in `docs/tools/beacon-chain/liquid-staking.md`
Best!
> docs: fix typos

- docs/node/management/withdrawals.md
- Use the correct `/eth/v1/beacon/pool/bls_to_execution_changes` URL in the withdrawals guide.
- See API spec: https://ethereum.github.io/beacon-APIs/#/Beacon/submitPoolBLSToExecutionChange
> Fix execution change POST URL

- docs/bridges/audits.md
- docs/developers/account-abstraction/safe.md
- Some minor typos are fixed
1. audits.md: fix a hyperlink
2. safe.md: "Ethrereum" corrected to "Ethereum".
> Fix some minor typo

- docs/developers/building/full-stack-dapp.md
- docs/developers/building/nft.md
- docs/developers/interact/rainbowkit-wagmi.mdx
> Fix several minor typo

- updates/2023/10-25-core-devs-call.md
> Gnosis Core Devs Call Notes October 25, 2023

- docs/node/management/voluntary-exit.md
- Added some missing informations about how to exit when the validator runs on Dappnode
- Added an extra warning in the "caution" section about needing a 0x01 withdrawal address before exiting
The extra warning doesn't hurt I think, we've seen unfortunate situations where people exited their validator with a 0x00 withdrawal address.
> Update voluntary-exit.md with Dappnode instructions

- docs/node/architecture.md
- Erigon seems to be ready to be used, so I removed the "in progress" comment next to it in `architecture.md`
- [Erigon's page in these docs](https://docs.gnosischain.com/node/manual/execution/erigon) state it is ready for production usage already.
- Unlike, e.g. [Geth](https://docs.gnosischain.com/node/manual/execution/geth)
> Remove "in progress" from Erigon

- docs/bridges/tutorials/using-amb.md
- Broken link because of typo (hhttps instead of https)
> hhttps -> https

- updates/2024/01-10-core-devs-call.md
> Core Devs Call Note January 10, 2024

- docs/bridges/tokenbridge/omnibridge.md
feeManager reference: https://gnosisscan.io/address/0xf6A78083ca3e2a662D6dd1703c939c8aCE2e268d#readProxyContract#F6
reading feeManager: https://gnosisscan.io/address/0x5dbc897aef6b18394d845a922bf107fa98e3ac55#readContract
sample with xPNK token, address https://gnosisscan.io/token/0x37b60f4e9a31a64ccc0024dce7d0fd07eaa0f7b3
likely outdated docs since fee is reproduced with:
- 0xe91d153e0b41518a2ce8dd3d7944fa863463a97d (wxdai)
- 0x6c76971f98945ae98dd7d4dfca8711ebea946ea6 (wsteth)
> correct fee on gnosis->mainnet omnibridge

- docs/node/guide/beacon/_partials/_install_cl_lighthouse.md
This PR update lighhouse client start command for chiado. 
As follows from [lighthouse documentation](https://lighthouse-book.sigmaprime.io/run_a_node.html#staking) its not necessary now to specify `--testnet-dir` flag which chould be replaced with the `--network chiado` as Chiado is fully supported.
> chore: update lighthouse chiado start cmmand

- docs/node/README.md
- docs/node/manual/execution/_partials/_install_el_nethermind.md
- docs/node/manual/execution/nethermind.md
- updates/2022/12-08-temporary-bootnodes.md
Updated the Nethermind executable name changed in v1.21.0. Although, `Nethermind.Runner` still works as a symlink on Linux and macOS; it may be dropped in future versions.
> Update Nethermind executable name

- docs/concepts/account-abstraction/particle-network.md
Particle Network recently released new documentation (https://developers.particle.network) and will soon be removing the old URL. Thus, this PR replaces the corresponding links with newer, more updated, and descriptive variants within the new documentation.
> Update links on particle-network.md

- docs/node/management/migrating-validator.md
- docs/node/management/monitoring-node.md
- docs/node/management/voluntary-exit.md
- docs/node/manual/beacon/lodestar.md
- docs/node/manual/validator/_partials/clients/_install_validator_lodestar.md
- docs/node/manual/validator/run/lodestar.md
- updates/2022/12-08-temporary-bootnodes.md
Update Lodestar documentation references, for flags we can now directly deep link instead of just to the CLI page, and also fixed a bunch of links of pages that got moved in docs refactor.
> Update Lodestar documentation references

- docs/node/manual/validator/run/lighthouse.md
Correct a small config paramaters. Have to use `validators-dir`
> fix: using datadir instead of validator-dir

- .github/workflows/dev_deploy.yml
- .github/workflows/prod_deploy.yml
- .github/workflows/tag_release.yml
In this PR we propose a change in the way the CI handles the deployments.
- Any commits to dev/main branches will trigger **dev_deploy.yml** which will build and deploy the website to the dev/staging environment.
- Any tagged commits will trigger **tag_release.yml** which will craft the Github Release on releases page
- Deployments to production are handled through a manual action which requires a valid tagged version as input.
> CI overhaul - handle manual deployments to production

- .github/workflows/prod_deploy.yml
- .github/workflows/slack_release_notification.yml
Introduces a new step in the CI, when triggering the release to production we also send a notification to a dedicated Slack channel containing info on the user and the outcome of the release, if successful or not.
> CI: Add slack_release_notifications.yml

- .github/workflows/tag_release.yml
- README.md
- docs/about/specs/hard-forks/dencun.md
- docs/about/specs/hard-forks/shanghai-capella.md
- docs/bridges/Build with Bridges/using-omnibridge/README.md
- docs/bridges/Build with Bridges/using-omnibridge/specific-tokens.md
- updates/2022/12-05-bridges-pause.md
- updates/2024/04-24-core-devs-call.md
- updates/2024/05-08-core-devs-call.md
- updates/archive/2020/xdai-weekly-recap-18-12-2020.md
- updates/archive/2021/xdai-weekly-recap-14-05-2021.md
> Please add severel core devs call notes! 

- docs/node/manual/validator/deposit.md
Due to the ongoing issues with the first version of the deposit UI (RPC connection failing), I created a short tutorial on how to run the UI locally with two changes:
- change RPC in ```wagmi.ts``` to ```https://gnosis-rpc.publicnode.com``` 
- change ```BLOCK_RANGE_SIZE``` in ```utils/fetchEvents.ts``` to ```10000```
This makes it "properly", with two **caveats**:
- The UI takes about 20 minutes to grab all data from the RPC
- The UI generates ```n``` deposit transactions for ```n``` validators, not only ```1``` deposit transaction for ```n``` validators as in the previous UI
(probably a separate issue)
I [forked the deposit UI](https://github.com/xdecentralix/gbc-deposit-ui) and deployed it with the changes here as well: [Working Deposit UI](https://gbc-deposit-ui.vercel.app/).
- don't …
> Added Option 3: "Running Your Own Deposit UI Instance Locally"

- docs/tools/Data Indexing/the-graph.md
The Graph just went fully decentralized. Past docs have become outdated. This PR contains the most up to date guide on using The Graph.
> updated docs on The Graph

- docs/about/tokens/gno.md
`mGNO` no longer serves any purpose. I'd remove it from the docs altogether, but it might still be useful to a tiny fraction of users. We can revisit the removal of any mention at some point.
> docs: update mGNO documentation

- docs/node/manual/configure-server.md
This PR fixes the rendering error in the generating JWT section of [the configure step](https://docs.gnosischain.com/node/manual/configure-server#create-jwt) in the documentation.
Changes:
From
to
> fix: correctly render jwt generation instruction from partials import

- docs/node/manual/execution/nethermind.md
Removed obsolete info, fixed Nethermind links, and slightly revised Nethermind configuration options. Removed the redundant trailing comma from the `--JsonRpc.EnabledModules`.
> Revise and fix Nethermind links

- docs/node/README.md
Hi! I fixes a broken link in the `node/README.md` file. The old link pointed to a deprecated or non-existent page for the Nethermind documentation. It has been updated to the correct and current URL.
> fix: update 404 link `node/README.md`

- docs/node/Node Tools/dappnode.md
I've corrected a few minor issues in the documentation text:  
- Removed the extra "the" in "the their official installation documentation."  
- Replaced "click in the package" with "click on the package" for better clarity.  
- Fixed a typo "becausethis" to "because this."  
- Corrected the spelling of "package chard" to "package chart."  
Thanks!
> docs: fixed typos and style inconsistencies in doc

- docs/faq/bridges.md
I’ve corrected a typo in the documentation. The word "depreciated" was used incorrectly and has been replaced with the correct term "deprecated" in the sentence:  
"The BSC - Gnosis Chain bridge has been **deprecated**. You can instead use a third-party bridge like Jumper for example."
> docs: fix typo in doc about BSC - Gnosis Chain bridge

- updates/2022/12-08-temporary-bootnodes.md
Hey team—noticed a dead link, replaced it with a working URL
https://chainsafe.github.io/lodestar/beacon-management/beacon-cli/#-bootnodes - old
https://chainsafe.github.io/lodestar/run/beacon-management/beacon-cli/#--bootnodes - new
> fix dead link 12-08-temporary-bootnodes.md

- docs/technicalguides/DeFi/Deploy A Cow Swap Widget.md
- update old `cowswap` github organization name to new `cowprotocol` in link.
very minor, no need for an issue
> Update Cow github organization name in Deploy A Cow Swap Widget.md

- docs/bridges/About Token Bridges/hashi-integration.md
- docs/bridges/hashi/README.md
- docs/bridges/hashi/hashi-integration.md
- docs/bridges/roadmap.md
- docs/technicalguides/DeFi/Deploy A Cow Swap Widget.md
- static/llms.txt
- updates/2025/05-21-core-devs-call.md
- updates/2025/05-28-core-devs-call.md
- updates/2025/06-04-core-devs-call.md
- updates/2025/06-25-core-devs-call.md
- updates/2025/07-02-core-devs-call.md
- updates/2025/07-09-core-devs-call.md
- updates/2025/07-16-core-devs-call.md
- updates/2025/07-23-core-devs-call.md
> Merging dev to main
