gnosischain/documentation

- src/css/custom.css
- centering images and iframes that are not width 100%
> Closes #33

- docusaurus.config.js
- package.json
- Measure visits, pageviews, and behavior of users navigating the website
- Issue #45
> closes #45 - google analytics

- docs/developers/interact/metamask.mdx
- src/pages/live-samples/metamask-add-button.js
- added docs to programmatically add token to Metamask w/ live example adding GNO
- https://github.com/gnosischain/documentation/issues/17
> added add custom token to metamask docs and added to the live example

- docs/bridges/tokenbridge/amb-bridge.md
> Remove Todo

- docs/about/overview/history.md
- docs/bridges/README.md
- docs/bridges/governance.md
- docs/bridges/thirdparty/connext.md
- docs/bridges/thirdparty/hop.md
- docs/bridges/tokenbridge/amb-bridge.md
- docs/bridges/tokenbridge/nft-bridge.md
- docs/bridges/tokenbridge/omnibridge.md
- docs/bridges/tokenbridge/xdai-bridge.md
- docs/bridges/tutorials/using-omnibridge.md
- docs/bridges/tutorials/using-xdai-bridge.md
- docs/developers/interact/README.md
- docs/ecosystems/README.md
- docusaurus.config.js
- sidebars.js
> Production Deploy (closes #60)

- .github/workflows/deploy.yml
- Setup CI with release branch to deploy into new environment.
- Setup Google Analytics variable for staging and prod environments.
- Comment production release webhook deployment.
> Setup new release CI deployment

- docs/bridges/audits.md
- added bridge audit history from https://docs.tokenbridge.net/about-tokenbridge/security-audits
- #73
> 73: Bridge Audits Page

- docs/ecosystems/README.md
- docs/ecosystems/daos.md
- docs/ecosystems/defi.md
- docs/ecosystems/games.md
- docs/ecosystems/infrastructure.md
- docs/ecosystems/nfts.md
- docs/ecosystems/tools-resources.md
- Organized the DApps
- Made UI slightly simpler
- Made some of the copy more professional
#87
> 87 ecosystem 2nd pass

- docs/about/tokens/gno.md
- added the security audit link
#79
> added the gno token audit link

- .github/workflows/deploy.yml
- Sets Google Analytics for release.
- Fix relase typo to release branch name.
> Fix Release deployment

- docs/tools/beacon-chain/liquid-staking.md
> Fix "ETH2" typos

- .github/workflows/deploy.yml
- docusaurus.config.js
> Google Analytics from ENV

- docusaurus.config.js
- static/robots.txt
- Search Functionality on Dev Site
- #24
> Search (closes #24)

- .github/workflows/deploy.yml
- reducing cache to 1 day (not 365)
- `sitemap.xml` no-cache
> cache 1 day, no-cache in sitemap.xml

- docs/ecosystems/README.md
Title was "Metamask" but links to the DAOs page
> Update wrong title (Metamask > DAOs)

- docs/ecosystems/nfts.md
Adding epor.io marketplace + text improvement
> Adding epor.io marketplace + text improvement

- docs/bridges/tokenbridge/amb-bridge.md
- docs/bridges/tokenbridge/omnibridge.md
- added updated validators
- got rid of circular reference in the AMB/OmniBridge validators sections
- #83
> Added updated validators

- docs/tools/rpc/README.mdx
Chainstack supports Gnosis Chain nodes + there's a tutorial for Gnosis Chain
> Add Chainstack as node provider

- docs/tools/explorers/README.md
- sidebars.js
- adding tokenview to the explorer list
> Adding tokenview to explorers (closes #119)

- docs/developers/interact/README.md
- docs/developers/interact/rainbowkit-wagmi.mdx
- sidebars.js
- Created a new section called "Using Rainbow Kit + Wagmi" that explains how to setup Rainbow Kit/Wagmi to accept Gnosis Chain as a custom chain
Adding sidebar.js link,  Interact/Readme link, and adding Rainbowkit+Wagmi guide within structure
> Adding Rainbowkit + Wagmi Explanation and Gnosis Chain setup

- docs/node/execution-layer-validator.md
- adding archive node configuration
> archive node configuration

- docs/node/execution-layer-validator.md
- Update information on how to run archive nodes
> Update archive nodes section

- docs/about/networks/README.md
- docs/about/networks/chiado.md
- docs/developers/interact/web3-js.md
- docs/developers/smart-contracts/foundry.md
- docs/developers/smart-contracts/hardhat.md
- docs/developers/smart-contracts/truffle.mdx
- docs/tools/rpc/README.mdx
- docs/tools/wallets/metamask/README.mdx
- Chiado testnet was restarted, with a different ChainID and resources
- [Chiado Testnet Discord Channel](https://discord.com/channels/502416149343109121/1006331943975125084)
> Chiado Reset Docs

- docs/about/networks/chiado.md
Hotfix for #179 
Will follow up with additional PR later today on full Chiado docs
> Add emergency notice

- docs/about/networks/chiado.md
Scaffold Chiado page with: 
- Config files
- Bridge addresses
- Staking contracts
> Add Bridge and Staking Addresses

- docs/node/validator-deposits.md
> Closes #164

- docs/node/validator-deposits.md
> Closes #163

- docs/about/networks/chiado.md
- rename GNO to Test GNO as specified in [issue-176](https://github.com/gnosischain/documentation/issues/176)
- [issue-176](https://github.com/gnosischain/documentation/issues/176)
> fix issue 176, rename GNO to Test GNO

- docs/about/networks/chiado.md
> Update of Chiado Networks page

- docs/node/consensus-layer-validator.md
- docs/node/execution-layer-validator.md
- Minimum viable changes to Validator Docs
- Further changes will be pushed to the "Run a Node" revamp
> Minimum viable docs site changes

- docs/node/get-started.md
- Add Gnosis Chain Merge Newsletter link.
- Add Discord link and information about the Praise Reward System.
> Add Discord and Merge Newsletter information.

- docs/tools/wallets/README.md
Added a dedicated section for gnosiswallets.com within the Wallets page.
- https://github.com/gnosischain/documentation/issues/205
> Update Wallets page with GnosisWallets.com

- docs/about/networks/chiado.md
- docs/specs/hard-forks/merge.md
- sidebars.js
- Add Merge page to Docs
- Update Chiado post-merge
> Add Merge page in Hardforks, update Chiado

- docs/specs/hard-forks/merge.md
> Fix broken links

- docs/node/consensus-layer/teku.md
- Updated teku.md
- https://github.com/gnosischain/documentation/issues/149
> WIP - 149 teku

- docs/node/consensus-layer/lodestar.md
- Updated lodestar.md
- https://github.com/gnosischain/documentation/issues/151
> WIP - 151 lodestar

- docs/node/guide/server/README.md
- docs/node/guide/server/configure-server.md
- docs/node/guide/server/jwt.md
- docs/node/guide/server/networking.md
- sidebars.js
> 231 prepare server

- docs/about/networks/chiado.md
- docs/about/tokens/gno.md
- docs/node/guide/validator/_partials/_fund-validator.md
- docs/node/guide/validator/deposit.md
- Refactor Fund Validator page
> 228 fund validator

- docs/node/guide/_partials/_multidimensional-content-controls-partial.md
- src/components/MultiDimensionalContentWidget.js
- src/css/custom.scss
- Disable tabs
- Apply to unsupported clients
> Disable Unsupported Clients

- docs/node/guide/beacon/lighthouse.md
- docs/node/guide/beacon/nimbus.md
- docs/node/guide/beacon/prysm.md
- docs/node/guide/execution/_partials/_install_el_nethermind.md
- docs/node/guide/server/_partials/_install-initial.md
- docs/node/guide/server/_partials/_jwt-generation-partial.md
- docs/node/guide/validator/_partials/_generate_validator_keys.md
- docs/node/guide/validator/_partials/clients/_install_validator_lighthouse.md
> Align folder structure and update CL warnings

- docs/specs/hard-forks/merge.md
- Added table with current client status
> Add client table with current status

- docs/node/guide/beacon/lighthouse.md
- docs/node/guide/beacon/lodestar.md
- docs/node/guide/beacon/teku.md
- docs/specs/hard-forks/merge.md
> 259 checkpoint sync

- docs/node/guide/beacon/_partials/_install_cl_lighthouse.md
- docs/node/guide/execution/_partials/_install_el_nethermind.md
- docs/node/guide/server/_partials/_jwt-generation-partial.md
- Openssl as default option
- Fix jwtsecret file names in interactive guide
> Closes #245 jwt default mode

- .gitignore
- docs/node/guide/README.md
- docs/node/guide/configure-server.md
- docs/node/guide/validator/_partials/_generate_validator_keys_cli.md
- docs/node/guide/validator/_partials/_generate_validator_keys_wagyu.md
- docs/node/guide/validator/generate-keys.md
- docs/node/guide/validator/generate-keys/README.md
- docs/node/guide/validator/generate-keys/cli/README.md
- docs/node/guide/validator/generate-keys/wagyu.md
- docs/node/tools/dappnode.md
- docusaurus.config.js
- sidebars.js
> Closes #247 - adding partial + refactor

- docs/node/guide/beacon/lighthouse.md
- docs/node/guide/beacon/lodestar.md
- docs/node/guide/beacon/teku.md
- docs/node/guide/execution/nethermind.md
- docs/node/guide/validator/run/lighthouse.md
- docs/node/guide/validator/run/lodestar.md
- docs/node/guide/validator/run/teku.md
> #268 #266 Change ports for EL and CL to default ports

- docs/node/management/migrating-validator.md
- docs/specs/hard-forks/README.md
- docs/specs/hard-forks/merge.md
> Migration warnings

- docs/specs/hard-forks/README.md
- docs/specs/hard-forks/merge.md
- Updated client availability table
- Added warnings re: risk of node not updated syncing to pre-fork version of the blockchain
> Updated client tables; merge hard fork warning

- docs/node/guide/execution/nethermind.md
Fix broken link in [Running Nethermind subsection](https://docs.gnosischain.com/node/guide/execution/nethermind#running-nethermind)
This is a broken link so there is no associated issue.
> chore: remove extra spaces to fix link

- docs/node/guide/README.md
- docs/node/guide/_partials/_install-intro.md
- docs/node/guide/beacon/_partials/_beacon_folder_structure.md
- docs/node/guide/beacon/_partials/_install_cl_lighthouse.md
- docs/node/guide/beacon/lighthouse.md
- docs/node/guide/beacon/lodestar.md
- docs/node/guide/beacon/prysm.md
- docs/node/guide/beacon/teku.md
- docs/node/guide/execution/_partials/_install_el_nethermind.md
- docs/node/guide/execution/nethermind.md
- docs/node/guide/server/_partials/_install-initial.md
- docs/node/guide/server/_partials/_jwt-generation-partial.md
- docs/node/guide/validator/_partials/_generate_validator_keys_cli.md
- docs/node/guide/validator/_partials/_monitor_logs_docker.md
- docs/node/guide/validator/_partials/_verify-validator.md
- docs/node/guide/validator/_partials/clients/_install_validator_lighthouse.md
- docs/node/guide/validator/generate-keys/README.md
- docs/node/guide/validator/run/lighthouse.md
- docs/node/guide/validator/run/lodestar.md
- docs/node/guide/validator/run/teku.md
- docusaurus.config.js
- sidebars.js
- src/components/MultiDimensionalContentWidget.js
Various fixes include:
- #275 
- #276 
- #270 
- #269 
- #227
- #238
- #240 
- #280
> Run node fixes

- docs/specs/hard-forks/merge.md
> Fix merge tables

- .github/workflows/deploy.yml
- docs/developers/README.md
- docs/developers/smart-contracts/README.md
- docs/ecosystems/README.md
- docs/specs/README.md
- docs/tools/README.md
- docusaurus.config.js
- sidebars.js
- src/css/custom.scss
- updates/202212-bridge-pause.md
- updates/202212-bridges-pause.md
- updates/authors.yml
- updates/post.template
- adding blog functionality under `updates`
- using [gnosis website](https://gnosis.io) font
- fixing react warning
> Website enhancements

- docusaurus.config.js
- updates/202212-bridges-pause.md
> WIP: 303 bridge pause announcement

- docs/bridges/governance/decisions.md
- docs/bridges/tokenbridge/amb-bridge.md
- docs/bridges/tokenbridge/omnibridge.md
- docs/bridges/tokenbridge/xdai-bridge.md
[Issue 306](https://github.com/gnosischain/documentation/issues/306)
> Bridge validators refresh documentation

- docusaurus.config.js
- package.json
- updates/20221210-merge.md
> Announce successful merge and that bridges have resumed operation

- docusaurus.config.js
- package.json
> Add temporary client-side redirects

- docusaurus.config.js
> Hotfix for Gateway's RPC URLs

- docs/about/networks/chiado.md
- docs/tools/rpc/README.mdx
> Update Chiado RPCs for Gateway

- docs/about/networks/chiado.md
- docs/about/networks/mainnet.md
- docs/tools/rpc/README.mdx
> Fix Gateway's Chiado RPC URL

- docs/node/faq.md
Replace https://gbc-deposit-old.herokuapp.com/ with https://mgno.validategnosis.com/
> Replace link to deposit UI

- docs/about/networks/mainnet.md
- updates/2022/12-08-temporary-bootnodes.md
> Execution bootnodes

- docs/node/tools/Validate Gnosis
- docs/node/tools/validategnosis.md
- Added Validate Gnosis (validategnosis.com) to Run a Node > Tools secction
-
> ValidateGnosis Validator Guide

- docs/tools/rpc/README.mdx
- Add BlockPI Network RPC reference and Public endpoint
> Add BlockPI Network RPC reference and Public endpoint

- docs/node/tools/dappnode.md
Grammar changes on Patience -> Patient and removal of double "the" in text.
> Grammar changes

- docs/tools/rpc/README.mdx
add endpoints 
https://gno.getblock.io/api_key/mainnet/
wss://gno.getblock.io/api_key/mainnet/
> Update details about GetBlock RPC Provider

- docs/about/networks/chiado.md
- Adds the beacon chain checkpoint sync URL
/
> docs: add beacon checkpoint sync URL

- updates/2023/01-25-core-devs-call.md
- updates/Gnosis Chain Core Devs Call - January 25, 2023.md
- updates/authors.yml
> Core Devs call

- updates/Gnosis Chain Core Devs Call - January 25, 2023.md
- Gnosis Chain Core Devs Call Notes - January 25, 2023
> Gnosis Chain Core Devs Call Notes - January 25, 2023

- docs/node/guide/README.md
- docs/node/guide/validator/_partials/clients/_install_validator_lighthouse.md
- Added introduction to explain **interactive guide** and **step-by-step**
> add intro in interactive guide #364

- docs/tools/oracles/SupraOracles/README.md
- docs/tools/oracles/SupraOracles/S-Value Price Feeds.md
- docs/tools/oracles/SupraOracles/VRF.md
- sidebars.js
- PR https://github.com/gnosischain/documentation/pull/361
- Minor format fixes (neutral tone, us=gnosis in the website)
- Added to menu
> SupraOracles

- docs/tools/oracles/SupraOracles/S-Value Price Feeds.md
- docs/tools/oracles/SupraOracles/VRF.md
Tailored SupraOracles docs for price feeds and VRF specific to Gnosis testnet.
> price feeds & VRF

- docs/tools/rpc/README.mdx
- sidebars.js
> Added BlockSpaces to the RPC providers

- docs/about/networks/chiado.md
- Fixed spelling from "isseud" to "issued" on line 75 in docs/about/network/chiado.md
> Fixed spelling in chiado.md

- docs/bridges/tutorials/using-omnibridge/safe.md
- docs/node/README.md
- Add **Choosing an approach** and **Spinning up the node** section under Run a Node's **Overview** page
-  Delete **Approach** section 
- [Ethereum's post "SPIN UP YOUR OWN ETHEREUM NODE"](https://ethereum.org/en/developers/docs/nodes-and-clients/run-a-node/)
> add Choosing approach and Spinning node section in Run a Node's Overview page

- docs/bridges/governance/decisions.md
- Added the latest governance decision for adjusting the bridge limits
> Added latest governance decision for adjusting the bridge limits

- docs/node/tools/dappnode.md
- Fix gnosis doc link for dAppNode
- Doc has been moved
> Fix gnosis doc link

- updates/2023/15-02-core-devs-call.md
- updates/2023/Gnosis Core Devs Call NotesFeb15.md
Added core devs call note for the docs.gnosischain.com
> Gnosis Core Devs Call Note Feb,15

- docs/about/networks/optimism.md
- alert message on https://docs.gnosischain.com/about/networks/optimism
> Deprecating optimism on GC

- updates/2023/03-08-core-devs-call.md
> Added March 8, 2023 Core Devs Call Notes

- updates/2023/03-22-core-devs-call.md
- updates/2023/Gnosis Core Devs Call Notes.md
> Added Core Devs Call Notes March 22, 2023

- updates/2023/03-29-core-devs-call.md
Added core devs call notes March 29, 2023
> Core Devs Call Notes March 29, 2023

- docs/developers/interact/dynamic.mdx
- sidebars.js
Adding documentation on how to use Gnosis Chain with Dynamic
- Dynamic is a free multi-chain wallet adapter with built in support for Gnosis Chain. We are proposing adding a guide to the Gnosis documentation next to other wallet libraries describing how to easily support Gnosis.
Note: I did not include the update to the overall documentation link structure as I assume that will be controlled by repo owners, but let me know if you'd like me to add it. Thanks!
The PR also includes a demo environment showing a full end to end working demo of the integration: https://codesandbox.io/s/dynamic-gnosis-chain-demo-vzps4b
Tackles two issues:
- Add Dynamic as an infra provider: https://github.com/gnosischain/documentation/issues/412
- Create a guide for how to use Dynamic with Gnosis Chain: …
> Gnosis Chain with Dynamic

- updates/2023/03-29-core-devs-call.md
- updates/2023/04-05-core-devs-call.md
> Added April 5, Core Devs Call Note

- updates/2023/04-12-core-devs-call.md
> Added Core Devs Call Note 12.4.2023

- docs/ecosystems/infrastructure.md
- Added Gelato one-line description and link into the Ecosystem Infrastructure paart
- n/a
> docs: add gelato to Infra

- updates/2023/04-26-core-devs-call.md
> Core Devs Call Notes April 26, 2023

- updates/2023/05-03-core-devs-call.md
> May 3 Core Devs Call Notes 

- updates/2023/05-10-core-devs-call.md
> May 10 Core Devs Call Notes

- updates/2023/05-17-core-devs-call.md
> May 17, Core Devs Call Notes

- docs/bridges/tokenbridge/omnibridge.md
- docs/bridges/tokenbridge/xdai-bridge.md
- docs/bridges/tutorials/using-xdai-bridge/no-ui.md
- docs/bridges/tutorials/using-xdai-bridge/safe.md
- docs/ecosystems/nfts.md
- docs/node/guide/beacon/lighthouse.md
- docs/node/management/voluntary-exit.md
> merge from main

- docs/about/networks/README.md
- docs/about/networks/chiado.md
- docs/about/networks/mainnet.md
- docs/about/networks/optimism.md
- docs/developers/interact/metamask.mdx
- docs/tools/wallets/metamask/README.mdx
- sidebars.js
- src/pages/live-samples/metamask-add-button.js
> content: Some updates

- updates/2023/03-15-core-devs-call.md
- updates/2023/04-19-core-devs-call.md
- updates/2023/04-26-core-devs-call.md
- updates/2023/05-10-core-devs-call.md
- updates/2023/05-24-core-devs-call.md
- minor: date fix
- unrelated content removal
> minor: date fix + unrelated content removal

- updates/2023/05-31-core-devs-call.md
> Core Devs Call May 31, 2023

- updates/2023/06-07-core-devs-call.md
> Core Devs Call Notes June 7, 2023

- updates/2023/06-14-core-devs-call.md
> Gnosis Core Devs Call Notes June 14

- updates/2023/06-21-core-devs-call.md
> Gnosis Core Devs Call Notes June 21, 2023

- docs/tools/rpc/README.mdx
- Adding chain49.com to list of RPC providers
---
Let me know if you need anything or something isn't right.
Thanks and best regards!
> Add Chain49 to list of RPC providers

- sidebars.js
- Added link to Chain49.com to sidebar menu. (I forgot to add this change to the first one, sorry!)
> Add Chain49 to sidebar menu

- docs/node/management/monitoring-node.md
- Added gnosispools.info under Monitoring your node(s) section
- Issue #435
> Added gnosispools.info 

- updates/2023/07-05-core-devs-call.md
> Core Devs Call Notes July 5

- updates/2023/07-12-core-devs-call.md
> Core Devs Call Notes July 12, 2023

- docs/node/management/withdrawals.md
- correct some spelling on the Node > Management > Withdrawals page
- (only typo fix)
> Spelling adjustments on node management withdrawals page

- docs/node/rewards-penalties.md
Added content onHow rewards are calculated in CL and EL for proposing and attesting blocks and how fee is burnt in EL.
Issue #396
> Added fee mechanism for rewards & penalties 

- updates/2023/08-02-core-devs-call.md
> Gnosis Core Devs Notes August 2, 2023

- docs/ecosystems/infrastructure.md
Added content about Add3 under Infrastructure docs
Issue #479
> Added content about Add3 under Infrastructure docs

- docs/node/tools/eth-docker.md
> fix: minor typo

- docs/node/README.md
- docs/node/guide/beacon/_partials/_install_cl_lodestar.md
- docs/node/guide/validator/_partials/clients/_install_validator_lodestar.md
- docs/node/guide/validator/run/lodestar.md
- docs/node/management/voluntary-exit.md
Update outdated Lodestar commands, this is likely incomplete, just updated the once I found quickly while browsing the docs.
Note: misc changes are due to auto-formatting
> Update outdated Lodestar commands

- updates/2023/08-09-core-devs-call.md
- updates/2023/Gnosis Core Devs Call Notes.md
> Gnosis Core Devs Call Notes Aug 9

- updates/2023/08-16-core-devs-call.md
> Gnosis Core Devs Call Notes Aug 16, 2023

- docs/tools/analytics/subquery.md
> Add SubQuery

- docs/tools/rpc/README.mdx
- Added OnFinality HTTP RPC endpoint for Gnosis
> Add OnFinality RPC endpoint for Gnosis

- updates/2023/08-30-core-devs-call.md
- updates/2023/09-06-core-devs-call.md
> Gnosis Core Devs Call Notes September 6, 2023

- docs/tools/rpc/README.mdx
> Fix typo for OnFinality RPC Endpoint

- docs/tools/wallets/README.md
Hi!! Apologies for my last submission, I somehow missed the replies.
Gnosis Chain is live in Enkrypt! Would love to be listed here <3
> Add Enkrypt to Wallets page.md

- docs/tools/explorers/README.md
Added 3xpl’s Gnosis explorer to the list
- Added 3xpl’s Gnosis explorer to the list of explorers.
> Added 3xpl explorer.md

- updates/2023/09-20-core-devs-call.md
> Gnosis Core Devs Call Notes September 20, 2023

- updates/2023/09-27-core-devs-call.md
> Gnosis Core Devs Call Notes September 27, 2023

- updates/2023/10-04-core-devs-call.md
> Gnosis Core Devs Call Notes October 4, 2023

- updates/2023/10-11-core-devs-call.md
> Gnosis Core Devs Call Notes October 11, 2023

- updates/2023/10-18-core-devs-call.md
> Gnosis Core Devs Call October 18, 2023

- docs/node/README.md
- docs/tools/rpc/README.mdx
- sidebars.js
Added Chainnodes to the list of providers. Chainnodes is an enterprise RPC provider for Ethereum and L2s with focus on low latency, archival and trace use cases.
> feat: add chainnodes to provider list

- docs/developers/account-abstraction/particle-network.md
- sidebars.js
This PR adds a page under the "Building Account Abstraction" section alongside Safe & Gelato for Particle Network. Aligning closely with the styling and structure of the Safe page, this runs through what Particle is, how Gnosis on Particle works, and dives into an example application.
> Adds Particle Network Account Abstraction page

- docs/ecosystems/defi.md
- Added description in the Ecosystem > DeFi section for SparkLend and Aave.
- Additionally, I added a description for savings xDAI in the Tokens section.
> add sparklend, aave and saving xDAI

- updates/2023/11-08-core-devs-call.md
> Gnosis Core Devs Call Notes November 08, 2023

- docs/ecosystems/tools-resources.md
- docs/tools/analytics/envio.md
- sidebars.js
- Added Envio under Data & Analytics on the Tools page
- Added Envio under Tools and Resources on Ecosystem page
> Add Envio under Data & Analytics section

- docs/tools/analytics/moralis.md
- sidebars.js
A brief intro to Moralis’ data tools to be listed in Gnosis Docs within the section "Data & Analytics" (e.g. https://docs.gnosischain.com/tools/analytics/the-graph).
> Article about Moralis APIs

- updates/2023/11-22-core-devs-call.md
> Gnosis Core Devs Call Notes November 22, 2023

- docs/node/manual/execution/erigon.md
- The default Dockerfile in this is outdated, updating the config.
- https://github.com/ledgerwatch/erigon/pull/7349/files
> Correct Erigon params in Dockerfile

- docs/developers/account-abstraction/particle-network.md
This PR includes a small update for the Particle Network AA tutorial adding some additional context and links.
> Updates Particle Network tutorial

- updates/2023/11-29-core-devs-call.md
> Core Devs Call Notes Nov 29, 2023

- docs/faq/node/runningNode.md
> Update FAQs  runningNode.md

- docs/faq/node/generalQuestions.md
- Re-do of https://github.com/gnosischain/documentation/pull/571
> 0xarmagan patch 1

- docs/faq/node/generalQuestions.md
> Fix missing answer in FAQs

- updates/2023/12-13-core-devs-call.md
> December 13, 2023 Core Devs Call Notes

- docs/node/README.md
- updates/2023/12-20-core-devs-call.md
> Core Devs call notes December 20, 2023

- docs/developers/README.md
A complete rewrite of the main page where developers land when they start with the developers section. It should include resources on how to get started. Theoretical part will be included in the concepts section later on.
> update developers overview

- docs/about/networks/chiado.md
- docs/about/networks/mainnet.md
- docs/developers/getting-started/contracts.md
- sidebars.js
Adding Useful Contracts page. It's much easier to do dev work when all contracts are on one page. The same approach uses Chainlink and all big blockchains in their docs.
> add contracts

- updates/2024/01-17-core-devs-call.md
> Gnosis Core Devs Call Notes Jan 17, 2023

- docusaurus.config.js
- sidebars.js
> move bridges into concepts

- updates/2024/01-24-core-devs-call.md
> January 24, 2024 Gnosis Core Devs Call Notes

- docs/concepts/specs/hard-forks/dencun.md
- sidebars.js
- Added details about dencun hardfork
> add dencun hardfork

- docusaurus.config.js
- Added redirected links for networks
> updated redirected links

- docs/developers/communication.md
- docs/node/README.md
- updates/2024/02-14-core-devs-call.md
> Added some links and edited node operators overview copies

- docusaurus.config.js
- sidebars.js
- src/components/HomepageFeatures/index.js
Adding bridging section as a proper sidebar for the navbar
> Updating bridging

- docusaurus.config.js
- updates/2024/02-21-core-devs-call.md
> pulling dev changes to v2-test-dev

- docs/node/management/monitoring-validators.md
> Add monitoring validators section

- updates/2024/03-27-core-devs-call.md
> Core Devs Call March 27, 2024

- README.md
- Update README, add instructions on the release process
> Update README, add instructions on deployments to production

- docs/about/specs/hard-forks/dencun.md
- docs/about/specs/hard-forks/shanghai-capella.md
- Updated compatible client mainnet versions on dancun hardfork page.
- Update dancun upgrade schedule table
- Add Shapella upgrade schedule table
- [hardforks schedule table source](https://github.com/gnosischain/specs/pull/44)
> chore: update hardforks info

- .github/workflows/tag_release.yml
- README.md
- docs/about/specs/hard-forks/dencun.md
- docs/about/specs/hard-forks/shanghai-capella.md
- docs/bridges/Build with Bridges/using-omnibridge/README.md
- docs/bridges/Build with Bridges/using-omnibridge/specific-tokens.md
- updates/2022/12-05-bridges-pause.md
- updates/2024/04-24-core-devs-call.md
- updates/archive/2020/xdai-weekly-recap-18-12-2020.md
- updates/archive/2021/xdai-weekly-recap-14-05-2021.md
> updates on docs

- docs/about/specs/README.md
- State that the EVM version on Gnosis Chain is Cancun
Unless I missed something the runtime is Cancun
> Update EVM Patchset

- docs/tools/Oracle Providers/pyth.md
> Add Pyth Oracle

- docs/tools/Oracle Providers/chronicle.md
> Add Chronicle to Oracles list

- docs/tools/Data Indexing/covalent.md
- Update Covalent content to reflect rebrand to GoldRush
- https://github.com/gnosischain/documentation/issues/693
> Update Covalent content to reflect rebrand to GoldRush

- docs/technicalguides/account-abstraction/zerodev-guide.md
* Merge main into dev (#665)
* Core Devs Call Notes April 18, 2024 (#660)
* Add files via upload
* new bridges draft - 1
* change bridge architecture
* bridges section update
* updated legacy links for bridges
* dev links updated
* links for bridges
* screenshots
* bridges ss
* fix(bridges): typo
* Core Devs Call April 3, 2024 (#654)
* fix: using datadir instead of validator-dir (#647)
* node structure and updates (#648)
* metadata test
* thumbnail
* thumbnail
* thumbnail fix
* thumbnail fix
* added image for metadata
* added image for metadata
* added image for metadata
* added image for metadata
* added image for metadata
* added image for metadata
* minor fixes
* Solve conflicts
* Add files via upload
* Update README.md
updated and edited some part
* Update depositWithdrawalReward.md
* …
> Backportin PR - Minor fix to zerodev guide (#700)

- docs/developers/Build contracts on gnosis/full-stack-dapp.md
- docs/tools/Blockchain Explorers/README.md
- docs/tools/Blockchain Explorers/blockscout.md
- docs/tools/README.md
- docs/tools/wallets/README.md
- updates/archive/2021/xdai-weekly-recap-09-07-2021.md
- updates/archive/2021/xdai-weekly-recap-21-05-2021.md
> chore: fix some comments

- docs/tools/web3-name-sdk.md
> doc: space id web3 name sdk

- docs/node/manual/execution/geth.md
- updates/2024/12-11-core-devs-call.md
Add instructions for running geth on gnosis chain
> Instructions for running geth

- docs/tools/Blockchain Explorers/tenderly.md
- docs/tools/Faucets.md
- Adding reference of Tenderly
- https://github.com/gnosischain/documentation/issues/753
> Add tenderly to blockchain explorers and faucets

- docs/node/architecture.md
Noticed a grammar mistake in the merge description:  
- **"Merged successful"** → **"Merged successfully"** (needed an adverb instead of an adjective).  
Fixed it to improve clarity.
> docs: fix grammar issue in merge description

- docs/bridges/usebridges.md
I fixed a couple of issues:
1. Changed "Dai" to "DAI" in the first section for proper capitalization.
2. Added the missing "to" in "Go the Gnosis Bridge UI."
These changes should make the text clearer.
> docs: Fix minor phrasing issues

- docs/node/manual/validator/_partials/_generate_validator_keys_cli.md
> fix: replace command line tool with eth staker deposit cli

- docs/node/Node Tools/eth-docker.md
- docs/node/management/monitoring-node.md
- docs/node/manual/validator/_partials/_generate_validator_keys_cli.md
- updates/2025/04-23-core-devs-call.md
- updates/2025/04-30-core-devs-call.md
- updates/2025/05-07-core-devs-call.md
- updates/2025/05-14-core-devs-call.md
> core devs call and ethstaker changes
